// Component Integration Hub
// Generated by Integration Bot

export { default as WeeklyPlan } from './WeeklyPlan';
export { default as MealFlowSelector } from './MealFlowSelector';
export { ExpandableCard, MealCard, WorkoutCard } from './ExpandableCards';
export { 
  MobileOptimizedWrapper, 
  ResponsiveGrid, 
  MobileModal, 
  TouchFriendlyButton 
} from './MobileComponents';

// Data exports
export { WORKOUT_DATABASE, getWorkoutsByCategory, getAllWorkouts } from '../data/workouts';
export { MEAL_DATABASE, getMealsByType, getAllMeals } from '../data/meals';

// Integration status
export const INTEGRATION_STATUS = {
  version: '1.0.0',
  components: [
    'WeeklyPlan',
    'MealFlowSelector', 
    'ExpandableCards',
    'MobileComponents'
  ],
  databases: [
    'workouts (165+ items)',
    'meals (structured flow)'
  ],
  styles: [
    'timeline.css',
    'cards.css',
    'responsive.css'
  ],
  timestamp: new Date().toISOString()
};